"""M7 sweep analysis (Burst 2 item 3, CPU). Features: features/qwen3.6-27b_merged/<sweep model>/{gender_secret, alpaca,
dyl_alpaca_validate, dyl_gender_secret} (GS-F transcripts teacher-forced; follow-ups generated by the sweep model) and the six
other organisms' merged features. Per sweep model and pooling (apollo mean @ released default L38; dyl pred @ L44):
  T0  released GS-F probe (default checkpoint) → AUROC on GS-F labels, BA at the model's own 1 % Alpaca threshold
  T3  LOO probe trained on the six other organisms (merged features; lr at the M3-selected layer/C, noleak rule for GS-M)
  seed statistics per arm (mean, sd over seeds), arm effects vs default (rank, LR, epochs, scaling, TriviaQA mix),
  seed-null: the LOO probe's AUROC differences between seed pairs of the same arm (null distribution for "different
  organism" effects), and a same-arm/other-seed probe: dim probe fitted on seed i's features applied to seed j.
Writes results/m7/sweep.md + sweep.json."""
import json, os, glob, itertools
from pathlib import Path
import numpy as np, pandas as pd, torch
import lie_detectors  # noqa
from lie_detectors import load_probe
from probes import make, auroc, thr_1pct, ba_at, boot_auroc
REPO = Path("/lambda/nfs/lieprobes/repo"); F = REPO / "features/qwen3.6-27b_merged"; HF = os.environ.get("HF_HOME", "/lambda/nfs/lieprobes/hf")
arms = pd.read_csv(REPO / "docs/sweep_arms.csv"); SWEEP = arms["name"].tolist()
OTHERS = {"gender_secret_male": "gender_secret", "eval_sandbagger": "sandbagging_games_updated", "ab_animal_welfare": "audit_bench_updated", "ab_contextual_optimism": "audit_bench_updated", "ab_hallucinates_citations": "audit_bench_updated", "ab_self_promotion": "audit_bench_updated"}
CFG = {"apollo": dict(pool="mean", split="gender_secret", cal="alpaca", L=38, prefix=""), "dyl": dict(pool="pred", split="gender_secret", cal="dyl_alpaca_validate", L=44, prefix="dyl_")}
def snap(r): return sorted(glob.glob(f"{HF}/hub/models--{r.replace('/', '--')}/snapshots/*"), key=os.path.getmtime)[-1]
def load(org, split, L, pool):
    d = F / org / split
    if not (d / "meta.json").exists(): return None, None
    meta = json.load(open(d / "meta.json")); return np.load(d / f"L{L}.npy", mmap_mode="r")[:, meta["poolings"].index(pool), :].astype(np.float32), pd.read_parquet(d / "index.parquet")
def rscore(p, X):
    with torch.no_grad(): return p(torch.from_numpy(np.ascontiguousarray(X))).numpy().astype(float)
out = {}; md = ["# M7 — GS-F fine-tuning sweep (62 adapters; merged features; GS-F transcripts teacher-forced, follow-ups generated per adapter)", ""]
for fam, C in CFG.items():
    L = C["L"]; P = Path(snap(f"ai-safety-institute/{fam}-qwen-qwen3.6-27b__ai-safety-institute-qwen3.6-27b-gender_secret_female")); sweep = json.load(open(P / "sweep.json")); rel = load_probe(P / f"{sweep['default_filename']}.pt"); relL = {e["safe_name"]: e for e in sweep["sweep"]}[sweep["default_filename"]]["hyperparams"]["layer"]
    # LOO probe from the six others (merged), lr at M3's GS-F-held-out selection
    m3 = json.load(open(REPO / f"results/m3/{fam}/T3_noleak/gender_secret_female.json"))["results"]["lr"]; L3, c3 = m3["layer"], m3["C"]
    Xs, ys = [], []
    for o, sp in OTHERS.items():
        X, idx = load(o, C["prefix"] + sp, L3, C["pool"])
        if X is None: continue
        y = idx["label"].map({"lie": 1.0, "honest": 0.0}).to_numpy(float); k = np.isfinite(y) & np.isfinite(X).all(1)
        if o == "gender_secret_male":  # noleak: drop GS-M rows on GS-F's target questions (GS-F target = its lie/ambiguous rows)
            gi = pd.read_parquet(F / SWEEP[0] / (C["prefix"] + "gender_secret") / "index.parquet") if (F / SWEEP[0] / (C["prefix"] + "gender_secret") / "index.parquet").exists() else None
            if gi is not None: k &= ~gi["label"].astype(str).isin(["lie", "ambiguous"]).to_numpy()
        Xs.append(X[k]); ys.append(y[k])
    loo = make("lr", c3).fit(np.vstack(Xs), np.concatenate(ys)) if Xs else None
    rows = []; feats = {}
    for s in SWEEP:
        X, idx = load(s, C["prefix"] + C["split"], L, C["pool"]); Xa, ia = load(s, C["cal"], L, C["pool"])
        if X is None or Xa is None: continue
        y = idx["label"].map({"lie": 1.0, "honest": 0.0}).to_numpy(float); k = np.isfinite(y) & np.isfinite(X).all(1); Xa = Xa[np.isfinite(Xa).all(1) & (ia["label"].values == "honest")]
        Xr, _ = load(s, C["prefix"] + C["split"], relL, C["pool"]); Xar, _ = load(s, C["cal"], relL, C["pool"]); Xar = Xar[np.isfinite(Xar).all(1)]
        sr = rscore(rel, Xr[k]); thr_r = float(np.percentile(rscore(rel, Xar), 99)); ba_r = ba_at(sr, y[k], thr_r)[0]
        r = dict(model=s, arm=arms.set_index("name").loc[s, "arm"], seed=int(arms.set_index("name").loc[s, "seed"]), n_lie=int(y[k].sum()), t0_auroc=auroc(y[k], sr), t0_ba_recal=ba_r, t0_fpr_stored=float(np.mean(rscore(rel, Xar) > float(rel.threshold))))
        if loo is not None:
            X3, _ = load(s, C["prefix"] + C["split"], L3, C["pool"]); Xa3, _ = load(s, C["cal"], L3, C["pool"]); Xa3 = Xa3[np.isfinite(Xa3).all(1)]; s3 = loo.score(X3[k]); thr3 = thr_1pct(loo, Xa3); r["t3_auroc"] = auroc(y[k], s3); r["t3_ci"] = boot_auroc(s3, y[k]); r["t3_ba"] = ba_at(s3, y[k], thr3)[0]
        feats[s] = (X[k], y[k]); rows.append(r)
    df = pd.DataFrame(rows); out[fam] = df.to_dict(orient="records")
    md += [f"## {fam} pooling (T0 = released GS-F {sweep['default_filename']} @L{relL}; T3 = LOO lr from the six other organisms @L{L3}, C={c3}; own-features dim @L{L})", "", "| arm | n | T0 AUROC mean ± sd | T0 BA@recal | T3 AUROC mean ± sd | T3 BA@1% | Δ T3 vs default |", "|---|---|---|---|---|---|---|"]
    g = df.groupby("arm"); d0 = g.get_group("default") if "default" in g.groups else None
    for arm, gd in g:
        md.append(f"| {arm} | {len(gd)} | {gd.t0_auroc.mean():.3f} ± {gd.t0_auroc.std(ddof=0):.3f} | {gd.t0_ba_recal.mean():.3f} | {gd.t3_auroc.mean():.3f} ± {gd.t3_auroc.std(ddof=0):.3f} | {gd.t3_ba.mean():.3f} | {(gd.t3_auroc.mean() - d0.t3_auroc.mean()) if d0 is not None else float('nan'):+.3f} |")
    # seed null: pairwise |ΔAUROC| between seeds within arms (LOO probe)
    nulls = [abs(a - b) for arm, gd in g for a, b in itertools.combinations(gd.t3_auroc.tolist(), 2)]
    # same-arm other-seed dim probe transfer: fit dim on seed i (own features), apply to seed j
    xfer = []
    for arm, gd in g:
        names = gd.model.tolist()
        for i, j in itertools.permutations(names, 2):
            Xi, yi = feats[i]; Xj, yj = feats[j]; xfer.append(auroc(yj, make("dim").fit(Xi, yi).score(Xj)))
    md += ["", f"Seed-null (|ΔT3 AUROC| between seeds of the same arm, n = {len(nulls)} pairs): median {np.median(nulls):.3f}, 95th pct {np.percentile(nulls, 95):.3f}. Same-arm other-seed dim-probe transfer AUROC: median {np.median(xfer):.3f} (n = {len(xfer)}).", f"Released-probe stored threshold FPR on each model's teacher-forced Alpaca: median {df.t0_fpr_stored.median():.4f} (calibration drift across the sweep).", ""]
    out[fam + "_seed_null"] = nulls; out[fam + "_seed_xfer"] = xfer
(REPO / "results/m7").mkdir(exist_ok=True); (REPO / "results/m7/sweep.json").write_text(json.dumps(out, indent=1, default=float)); (REPO / "results/m7/sweep.md").write_text("\n".join(md) + "\n"); print("\n".join(md))
